apiVersion: v1
kind: Service
metadata:
  name: 2048-service
  namespace: 2048-game
spec:
  selector:
    app: 2048-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80   # FIX: changed from 3000 to 80
  type: NodePort
